# SPDX-License-Identifier: GPL-2.0
#
# AXERA Clock Drivers
#
obj-$(CONFIG_COMMON_CLK_AXERA) += clk.o
obj-$(CONFIG_COMMON_CLK_AX650X) += clk-ax650x.o
obj-$(CONFIG_COMMON_CLK_AX650X) += clk-pll-ax650x.o
