from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs += SConscript(os.path.join(item, 'SConscript'))

objs     += Glob('*.c')
CPPPATH = [cwd]

group   = DefineGroup('ax_app', objs, depend = [''], CPPPATH = CPPPATH, LIBRARY = ["ax_app"])
Return('group')
