#ifndef __DTS_AX650_OPTEE_DEFINE_H
#define __DTS_AX650_OPTEE_DEFINE_H

#ifdef OPTEE_BOOT
#define OPTEE_RESERVED_START_HI
#define OPTEE_RESERVED_START_LO
#define OPTEE_RESERVED_SIZE_HI
#define OPTEE_RESERVED_SIZE_LO
#endif

#endif /* __DTS_AX650_OPTEE_DEFINE_H */
