/**************************************************************************************************
 *
 * Copyright (c) 2019-2024 Axera Semiconductor Co., Ltd. All Rights Reserved.
 *
 * This source file is the property of Axera Semiconductor Co., Ltd. and
 * may not be copied or distributed in any isomorphic form without the prior
 * written consent of Axera Semiconductor Co., Ltd.
 *
 **************************************************************************************************/

#pragma once
#include "ax_base_type.h"
#include "ax_vo_api.h"


typedef struct VO_CHN_INFO_S
{
    AX_U32 nCount;                            /* number of valid arrChns, [1 - AX_VO_CHN_MAX]  */
    AX_F32 arrFps[AX_VO_CHN_MAX];            /* if PTS of 1st frame is 0, VO is in charge of calculate PTS according fps */
    AX_BOOL arrHidden[AX_VO_CHN_MAX];        /* if PTS of 1st frame is 0, VO is in charge of calculate PTS according fps */
    AX_VO_CHN_ATTR_T arrChns[AX_VO_CHN_MAX]; /* rectage: x y w h shoule be even alignment, width stride should align to 16 */
} VO_CHN_INFO_T;
typedef struct SAMPLE_VO_ATTR_S
{
    VO_DEV dev;            /* [IN ] 0: HDMI0  1: HDMI1 */
    VO_LAYER voLayer;      /* [OUT] layer is generated by VO */
    AX_S32 s32FBIndex[2];  /* [IN ] 0: QT 1: Overlay */
    AX_VO_INTF_TYPE_E enIntfType;     /* [IN ] default: AX_VO_INTF_HDMI */
    AX_VO_INTF_SYNC_E enIntfSync;     /* [IN ] default: AX_VO_OUTPUT_1080P60 */
    AX_VO_OUT_FMT_E enIntfFmt;        /*[IN ] default:  AX_VO_OUT_FMT_UNUSED ==> RGB888 */
    AX_BOOL bForceDisplay;            /* [IN ] AX_TRUE: force display ignore EDID, default: AX_TRUE */
    AX_BOOL bLinkVo2Disp;             /* [IN ] AX_FALSE: Unlink mode gives users the ability to get layer frame before send to DISP */
    AX_VO_ENGINE_MODE_E enEngineMode; /* [IN ] if nEngineId == 3, set to AX_VO_ENGINE_MODE_FORCE, default: AX_VO_ENGINE_MODE_AUTO */
    AX_U32 nEngineId;                 /* [IN ] 0: VO0 1: VO1, 3: TDP */
    AX_U32 nBgClr;                    /* [IN ] background color, fmt: RGB888 */
    AX_U32 nLayerDepth;               /* [IN ] layer depth, [3 - ], if less than 3, set to 3 */
    VO_CHN_INFO_T stChnInfo;          /* [IN ] */
    AX_VO_PART_MODE_E enDrawMode;     /* [IN ] draw mode, PIP pipe: single */
    AX_VO_MODE_E enVoMode;            /* [IN ] vo mode, online or offline, default: AX_VO_MODE_OFFLINE*/
    AX_VO_LAYER_SYNC_MODE_E enSyncMode;
    AX_HDMI_ATTR_T stHdmiAttr;
} SAMPLE_VO_ATTR_T;

AX_BOOL SAMPLE_VO_Init(AX_U32 nW, AX_U32 nH, AX_U8 nFps, AX_BOOL bShowFb, AX_BOOL bYuv422_10bit);
AX_BOOL SAMPLE_VO_Start();
AX_BOOL SAMPLE_VO_Stop();
AX_BOOL SAMPLE_VO_DeInit();