ifdef CONFIG_VIDEO_AXERA
obj-y += dw_mipi_dsi.o
obj-y += ax_dw_mipi_dsi.o
obj-y += dw_hdmi.o
obj-y += ax_dw_hdmi.o
obj-y += ax_vo.o
obj-y += ax650_vo_common.o
obj-y += ax650_vo.o
obj-y += ax650_mm_ck.o
obj-y += ax_simple_logo.o
obj-y += ax_simple_logo_cfg.o
endif
