#ifndef __CHIP_REG_H__
#define __CHIP_REG_H__

#define CPU_CK_RST_CFG               0x4516000
#define CPU_CK_RST_CFG_CLK_MUX0      (CPU_CK_RST_CFG + 0x0)
#define CPU_CK_RST_CFG_CLK_MUX0_SET  (CPU_CK_RST_CFG + 0x10)

#define COMM_CK_RST_CFG               0x4210000  //aon_clk_rst
#define COMM_CK_RST_CFG_CLK_MUX0_SET  (COMM_CK_RST_CFG + 0x28)
#define COMM_CK_RST_CFG_CLK_MUX1_SET  (COMM_CK_RST_CFG + 0x30)
#define COMM_CK_RST_CFG_CLK_EB1_SET   (COMM_CK_RST_CFG + 0x40)
#define COMM_CK_RST_CFG_CLK_EB1_CLR   (COMM_CK_RST_CFG + 0x44)

#define COMM_SYS_GLB		0x4200000 //aon_glb
#define COMM_SYS_CHIP_MODE	(COMM_SYS_GLB + 0x10)
#define COMM_SYS_CHIP_BOND	(COMM_SYS_GLB + 0x14)
#define COMM_SYS_BOND_OPT0	(COMM_SYS_GLB + 0x20)
#define COMM_SYS_BOND_OPT1	(COMM_SYS_GLB + 0x24)
#define COMM_SYS_MISC_CTRL	(COMM_SYS_GLB + 0x13c)
#define COMM_SYS_DUMMY_SW5	(COMM_SYS_GLB + 0x1B4)
#define COMM_SYS_DMA_FLASH_DW_SEL0	(COMM_SYS_GLB + 0x3d4)
#define COMM_SYS_DMA_FLASH_DW_SEL1	(COMM_SYS_GLB + 0x3d8)

#define PERI_CLK_RST_CFG                (0x2002000)
#define PERI_CLK_RST_CFG_MUX0           (PERI_CLK_RST_CFG + 0x0)
#define PERI_CLK_RST_CFG_MUX0_SET       (PERI_CLK_RST_CFG + 0x38)
#define PERI_CLK_RST_CFG_MUX0_CLR       (PERI_CLK_RST_CFG + 0x3C)
#define PERI_CLK_RST_CFG_EB0_SET        (PERI_CLK_RST_CFG + 0x40)
#define PERI_CLK_RST_CFG_EB1_SET        (PERI_CLK_RST_CFG + 0x48)
#define PERI_CLK_RST_CFG_EB2_SET        (PERI_CLK_RST_CFG + 0x50)
#define PERI_CLK_RST_CFG_EB4_SET        (PERI_CLK_RST_CFG + 0x60)
#define PERI_CLK_RST_CFG_EB5_SET        (PERI_CLK_RST_CFG + 0x68)
#define PERI_CLK_RST_CFG_SW_RST0_CLR    (PERI_CLK_RST_CFG + 0x7c)
#define PERI_CLK_RST_CFG_SW_RST3_CLR    (PERI_CLK_RST_CFG + 0x94)

#define FLASH_SYS_GLB		0x100000
#define FLASH_SYS_CLK_RST_BASE 0x110000
#define FLASH_SYS_CLK_RST_CLK_MUX0 (FLASH_SYS_CLK_RST_BASE + 0x0)
#define FLASH_SYS_CLK_RST_CLK_EB_0 (FLASH_SYS_CLK_RST_BASE + 0x4)
#define FLASH_SYS_CLK_RST_CLK_EB_1 (FLASH_SYS_CLK_RST_BASE + 0x8)
#define FLASH_SYS_CLK_RST_CLK_DIV_0 (FLASH_SYS_CLK_RST_BASE + 0xC)
#define FLASH_SYS_CLK_RST_SW_RST_0 (FLASH_SYS_CLK_RST_BASE + 0x10)
#define FLASH_SYS_CLK_RST_CLK_MUX0_SET (FLASH_SYS_CLK_RST_BASE + 0x18)
#define FLASH_SYS_CLK_RST_CLK_MUX0_CLR (FLASH_SYS_CLK_RST_BASE + 0x1C)
#define FLASH_SYS_CLK_RST_CLK_EB_0_SET (FLASH_SYS_CLK_RST_BASE + 0x20)
#define FLASH_SYS_CLK_RST_CLK_EB_0_CLR (FLASH_SYS_CLK_RST_BASE + 0x24)
#define FLASH_SYS_CLK_RST_CLK_EB_1_SET (FLASH_SYS_CLK_RST_BASE + 0x28)
#define FLASH_SYS_CLK_RST_CLK_EB_1_CLR (FLASH_SYS_CLK_RST_BASE + 0x2C)
#define FLASH_SYS_CLK_RST_CLK_DIV_0_SET (FLASH_SYS_CLK_RST_BASE + 0x30)
#define FLASH_SYS_CLK_RST_CLK_DIV_0_CLR (FLASH_SYS_CLK_RST_BASE + 0x34)
#define FLASH_SYS_CLK_RST_SW_RST_0_SET (FLASH_SYS_CLK_RST_BASE + 0x38)
#define FLASH_SYS_CLK_RST_SW_RST_0_CLR (FLASH_SYS_CLK_RST_BASE + 0x3C)

#define GTMR_BASE 0x140000

#ifdef RLT09_TAG0115
#define FLASH_SYS_GLB		0x100000
#define FLASH_SYS_CLK_RST	0x110000
#define FLASH_SYS_CLK_MUX0	(FLASH_SYS_CLK_RST + 0x0)
#define FLASH_SYS_CLK_EB_0_SET	(FLASH_SYS_CLK_RST + 0x18)
#define FLASH_SYS_CLK_EB_1_SET	(FLASH_SYS_CLK_RST + 0x20)
#define FLASH_SYS_SW_RST_0_CLR	(FLASH_SYS_CLK_RST + 0x2c)
#endif

#define SYS_IRAM_BASE		(0x4800000)
#define SYS_OCM_BASE		0x14000000
#define SYS_DRAM_BASE		0x100000000

#define NPU_CK_RST_BASE         (0x16550000)
#define NPU_CK_RST_CLK_EB0      (NPU_CK_RST_BASE + 0x4)
#define NPU_CK_RST_CLK_EB1      (NPU_CK_RST_BASE + 0x8)
#define NPU_CK_RST_CLK_RST      (NPU_CK_RST_BASE + 0xC)
#define NPU_CK_RST_CLK_EB0_SET  (NPU_CK_RST_BASE + 0x28)
#define NPU_CK_RST_CLK_EB0_CLR  (NPU_CK_RST_BASE + 0x2C)

#define PMU_GLB_BASE		(0x04C00000)
#define PMU_GLB_WAKEUP		(PMU_GLB_BASE + 0x8)
#define PMU_GLB_WAKEUP1		(PMU_GLB_BASE + 0xC)
#define PMU_GLB_PWR_STATE3	(PMU_GLB_BASE + 0x24)

#ifdef RLT09_TAG0115
#define PERI_SYS_GLB			(0x02000000)
#define PERI_SYS_CLK_RST		(0x02002000)
#define PERI_SYS_CLK_EB_4_SET		(PERI_SYS_CLK_RST + 0x5c)
#define PERI_SYS_SW_RST_0_CLR		(PERI_SYS_CLK_RST + 0x78)
#endif
#define GPIO0_BASE			0x02003000
#define GPIO1_BASE			0x02004000
#define GPIO2_BASE			0x02005000
#define GPIO3_BASE			0x02006000
#define GPIO4_BASE			0x02007000
#define PORTA_DR			0x00
#define PORTA_DDR			0x04
#define PORTA_CTL			0x08

#define PIN_MUX_G3_BASE			0x04250200

#define PIN_MUX_G4_BASE			0x04250400
#define PIN_MUX_G4_PINCTRL		(PIN_MUX_G4_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G4_PINCTRL_SET	(PIN_MUX_G4_BASE + 0x4)
#define PIN_MUX_G4_PINCTRL_CLR	(PIN_MUX_G4_BASE + 0x8)
#define PIN_MUX_G4_PAD_ROL		(PIN_MUX_G4_BASE + 0x12C)//bit24

#define PIN_MUX_G5_BASE			0x04250600
#define PIN_MUX_G5_PINCTRL		(PIN_MUX_G5_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G5_PINCTRL_SET	(PIN_MUX_G5_BASE + 0x4)
#define PIN_MUX_G5_PINCTRL_CLR	(PIN_MUX_G5_BASE + 0x8)
#define PIN_MUX_G5_PAD_ROL		(PIN_MUX_G5_BASE + 0x84)//bit10

#define PIN_MUX_G6_BASE			0x04250800

#define PIN_MUX_G7_BASE			0x04250A00
#define PIN_MUX_G7_PINCTRL		(PIN_MUX_G7_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G7_PINCTRL_SET	(PIN_MUX_G7_BASE + 0x4)
#define PIN_MUX_G7_PINCTRL_CLR	(PIN_MUX_G7_BASE + 0x8)
#define PIN_MUX_G7_PAD_ROL		(PIN_MUX_G7_BASE + 0x9C)//bit12

#define PIN_MUX_G8_BASE			0x04250C00
#define PIN_MUX_G8_PINCTRL		(PIN_MUX_G8_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G8_PINCTRL_SET	(PIN_MUX_G8_BASE + 0x4)
#define PIN_MUX_G8_PINCTRL_CLR	(PIN_MUX_G8_BASE + 0x8)
#define PIN_MUX_G8_PAD_ROL		(PIN_MUX_G8_BASE + 0xCC)//bit16

#define PIN_MUX_G9_BASE			0x04250E00
#define PIN_MUX_G9_PINCTRL		(PIN_MUX_G9_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G9_PINCTRL_SET	(PIN_MUX_G9_BASE + 0x4)
#define PIN_MUX_G9_PINCTRL_CLR	(PIN_MUX_G9_BASE + 0x8)
#define PIN_MUX_G9_PAD_ROL		(PIN_MUX_G9_BASE + 0x84)//bit10

#define PIN_MUX_G10_BASE		0x04251000
#define PIN_MUX_G10_PINCTRL		(PIN_MUX_G10_BASE + 0x0)//bit[8:7]
#define PIN_MUX_G10_PINCTRL_SET	(PIN_MUX_G10_BASE + 0x4)
#define PIN_MUX_G10_PINCTRL_CLR	(PIN_MUX_G10_BASE + 0x8)

/* vdet enable address
bit[0]    : en_vdet_g4, default 1
bit[1]    : en_vdet_g5, default 1
bit[2]    : en_vdet_g7, default 1
bit[3]    : en_vdet_g8, default 1
bit[4]    : en_vdet_g9, default 1
bit[5]    : en_vdet_g10, default 1
*/
#define PIN_MUX_G10_MISC		(PIN_MUX_G10_BASE + 0xAC)//bit[8:7]
#define PIN_MUX_G10_PAD_ROL		(PIN_MUX_G10_BASE + 0xA8)//bit13

#define PIN_MUX_EMMC_BASE		0x04251e00

#define PIPE_SYS_CLK_BASE               0x30010000
#define PIPE_SYS_CLK_MUX_0              (PIPE_SYS_CLK_BASE + 0x0)
#define PIPE_SYS_CLK_MUX_0_SET          (PIPE_SYS_CLK_BASE + 0x18)
#define PIPE_SYS_CLK_EB0_SET            (PIPE_SYS_CLK_BASE + 0x20)
#define PIPE_SYS_CLK_EB0_CLR            (PIPE_SYS_CLK_BASE + 0x24)
#define PIPE_SYS_CLK_EB1_SET            (PIPE_SYS_CLK_BASE + 0x28)
#define PIPE_SYS_CLK_EB1_CLR            (PIPE_SYS_CLK_BASE + 0x2C)
#define PIPE_SYS_CLK_DIV_0_SET          (PIPE_SYS_CLK_BASE + 0x30)
#define PIPE_SYS_CLK_DIV_0_CLR          (PIPE_SYS_CLK_BASE + 0x34)
#define PIPE_SYS_SW_RESET_SET           (PIPE_SYS_CLK_BASE + 0x38)
#define PIPE_SYS_SW_RESET_CLR           (PIPE_SYS_CLK_BASE + 0x3C)

#endif
