#!/bin/sh

DEST_FILE=$1
OPTEE_RESERVED_START=$2
OPTEE_RESERVED_SIZE=$3

echo "start optee dts handle...."
echo $2 $3
sed -i '/#ifdef/i #define OPTEE_BOOT' $DEST_FILE

OPTEE_RES_START_LOW=$(printf "0x%x\n" $(($OPTEE_RESERVED_START & 0xFFFFFFFF)))
OPTEE_RES_START_HIGH=$(printf "0x%x\n" $(($OPTEE_RESERVED_START >> 32)))
OPTEE_RES_SIZE_LOW=$(printf "0x%x\n" $(($OPTEE_RESERVED_SIZE & 0xFFFFFFFF)))
OPTEE_RES_SIZE_HIGH=$(printf "0x%x\n" $(($OPTEE_RESERVED_SIZE >> 32)))

sed -i "s/OPTEE_RESERVED_START_HI/OPTEE_RESERVED_START_HI $OPTEE_RES_START_HIGH/g" $DEST_FILE
sed -i "s/OPTEE_RESERVED_START_LO/OPTEE_RESERVED_START_LO $OPTEE_RES_START_LOW/g" $DEST_FILE
sed -i "s/OPTEE_RESERVED_SIZE_HI/OPTEE_RESERVED_SIZE_HI $OPTEE_RES_SIZE_HIGH/g" $DEST_FILE
sed -i "s/OPTEE_RESERVED_SIZE_LO/OPTEE_RESERVED_SIZE_LO $OPTEE_RES_SIZE_LOW/g" $DEST_FILE
