#ifndef __CPU_SYS_COMM_GLB_H__
#define __CPU_SYS_COMM_GLB_H__

#include <ax650_def.h>

// REGISTER : RVBARADDR_LO_CORE0

#define CPU_SYS_COMM_GLB_RVBARADDR_LO_CORE0_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x4)

// REGISTER : RVBARADDR_HI_CORE0

#define CPU_SYS_COMM_GLB_RVBARADDR_HI_CORE0_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x8)

// REGISTER : CPU_SYS_SLEEP_EN_SET

#define CPU_SYS_COMM_GLB_CPU_SYS_SLEEP_EN_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x102C)
#define BIT_CPU_SYS_CPU_SYS_SLEEP_EN_SET                BIT(8)

// REGISTER : CPU_INT_DISABLE_SET

#define CPU_SYS_COMM_GLB_CPU_INT_DISABLE_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x100C)

// REGISTER : CA55_CORES_PCHN_ACTIVE_TIMEOUT

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_ACTIVE_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x30)
#define BIT_CPU_SYS_CORES_PCHN_ACTIVE_TIMEOUT_EN    BIT(16)

// REGISTER : CA55_CORES_PCHN_REQ_TIMEOUT

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_REQ_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x34)
#define BIT_CPU_SYS_CORES_PCHN_REQ_TIMEOUT_EN        BIT(16)

// REGISTER : CA55_CORES_PCHN_DENY_TIMEOUT

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_DENY_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x38)
#define BIT_CPU_SYS_CORES_PCHN_DENY_TIMEOUT_EN        BIT(16)

// REGISTER : CA55_CORE0_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE0_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x3C)

// REGISTER : CA55_CORE1_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE1_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x40)
#define BIT_CPU_SYS_A55_CORE_P_CHN_WAKEUP               BIT(8)

// REGISTER : CA55_CORE2_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE2_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x44)

// REGISTER : CA55_CORE3_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE3_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x48)

// REGISTER : CA55_CORE4_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE4_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x4C)

// REGISTER : CA55_CORE5_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE5_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x50)

// REGISTER : CA55_CORE6_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE6_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x54)

// REGISTER : CA55_CORE7_P_CHN_CFG

#define CPU_SYS_COMM_GLB_CA55_CORE7_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x58)

// REGISTER : DSU_P_CHN_CFG

#define CPU_SYS_COMM_GLB_DSU_P_CHN_CFG_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x5C)
#define CPU_SYS_COMM_GLB_DSU_P_CHN_CFG_MASK_POS      16
#define CPU_SYS_COMM_GLB_DSU_P_CHN_CFG_MASK_MASK     0x7FFF0000
#define CPU_SYS_COMM_GLB_DSU_P_CHN_CFG_REG_WAKEUP_POS      8
#define CPU_SYS_COMM_GLB_DSU_P_CHN_CFG_FRC_ON_POS      0

// REGISTER : DSU_P_CHN_ACTIVE_TIMEOUT

#define CPU_SYS_COMM_GLB_DSU_P_CHN_ACTIVE_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x60)
#define BIT_DSU_P_CHN_ACTIVE_TIMEOUT_EN      BIT(16)

// REGISTER : DSU_P_CHN_REQ_TIMEOUT

#define CPU_SYS_COMM_GLB_DSU_P_CHN_REQ_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x64)
#define BIT_DSU_P_CHN_REQ_TIMEOUT_EN      BIT(16)

// REGISTER : DSU_P_CHN_DENY_TIMEOUT

#define CPU_SYS_COMM_GLB_DSU_P_CHN_DENY_TIMEOUT_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x68)
#define BIT_DSU_P_CHN_DENY_TIMEOUT_EN      BIT(16)


// REGISTER : CA55_CORE0_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE0_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x103C)
#define BIT_CPU_SYS_A55_CORE_P_CHN_WAKEUP_SET               BIT(8)

// REGISTER : CA55_CORE1_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE1_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1040)

// REGISTER : CA55_CORE2_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE2_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1044)

// REGISTER : CA55_CORE3_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE3_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1048)

// REGISTER : CA55_CORE4_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE4_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x104C)

// REGISTER : CA55_CORE5_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE5_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1050)
// REGISTER : CA55_CORE6_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE6_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1054)

// REGISTER : CA55_CORE7_P_CHN_CFG_SET

#define CPU_SYS_COMM_GLB_CA55_CORE7_P_CHN_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1058)

// REGISTER : DSU_P_CHN_ACTIVE_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_DSU_P_CHN_ACTIVE_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1060)
#define BIT_DSU_P_CHN_ACTIVE_TIMEOUT_SET_UPDATE_SET    BIT(24)


// REGISTER : DSU_P_CHN_REQ_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_DSU_P_CHN_REQ_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1064)
#define BIT_DSU_P_CHN_REQ_TIMEOUT_SET_UPDATE_SET    BIT(24)


// REGISTER : DSU_P_CHN_DENY_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_DSU_P_CHN_DENY_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1068)
#define BIT_DSU_P_CHN_DENY_TIMEOUT_SET_UPDATE_SET    BIT(24)

// REGISTER : CPU_SYS_SLEEP_EN_CLR

#define CPU_SYS_COMM_GLB_CPU_SYS_SLEEP_EN_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x202C)

// REGISTER : CA55_CORE0_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE0_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x203C)
#define BIT_CPU_SYS_A55_CORE_P_CHN_WAKEUP_CLR               BIT(8)

// REGISTER : CA55_CORE1_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE1_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2040)

// REGISTER : CA55_CORE2_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE2_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2044)

// REGISTER : CA55_CORE3_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE3_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2048)

// REGISTER : CA55_CORE4_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE4_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x204C)

// REGISTER : CA55_CORE5_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE5_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2050)

// REGISTER : CA55_CORE6_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE6_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2054)

// REGISTER : CA55_CORE7_P_CHN_CFG_CLR

#define CPU_SYS_COMM_GLB_CA55_CORE7_P_CHN_CFG_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2058)

// REGISTER : DSU_P_CHN_ACTIVE_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_DSU_P_CHN_ACTIVE_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2060)
#define BIT_DSU_P_CHN_ACTIVE_TIMEOUT_CLR_UPDATE_CLR    BIT(24)

// REGISTER : DSU_P_CHN_REQ_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_DSU_P_CHN_REQ_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2064)
#define BIT_DSU_P_CHN_REQ_TIMEOUT_CLR_UPDATE_CLR    BIT(24)

// REGISTER : DSU_P_CHN_DENY_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_DSU_P_CHN_DENY_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2068)
#define BIT_DSU_P_CHN_DENY_TIMEOUT_CLR_UPDATE_CLR    BIT(24)

// REGISTER : CPU_SYS_LIGHT_SLP_CFG_SET

#define CPU_SYS_COMM_GLB_CPU_SYS_LIGHT_SLP_CFG_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x109C)
#define BIT_CPU_SYS_COMM_GLB_CPU_SYS_LIGHT_SLP_CFG_DATA_IDLE_EN_SET      BIT(8)
#define BIT_CPU_SYS_COMM_GLB_CPU_SYS_LIGHT_SLP_CFG_SET_LIGHT_SLP_EN_SET_POS      0

// REGISTER : EIC_EN_SET

#define CPU_SYS_COMM_GLB_EIC_EN_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1098)
#define BIT_EIC_EN_MAIL0_SET    BIT(9)
#define BIT_EIC_EN_DEB_GPIO_SET    BIT(8)
#define BIT_EIC_EN_RTC0_SET    BIT(7)
#define BIT_EIC_EN_RTC1_SET    BIT(6)
#define BIT_EIC_EN_RTC2_SET    BIT(5)
#define BIT_EIC_EN_RTC3_SET    BIT(4)
#define BIT_EIC_EN_WDT0_SET    BIT(3)
#define BIT_EIC_EN_TMR32_SET    BIT(2)
#define BIT_EIC_EN_TMR64_SET    BIT(1)
#define BIT_EIC_EN_GPIO_SET    BIT(0)
#define BITS_EIC_EN_ALL     0x3FF


// REGISTER : CA55_CORES_PCHN_ACTIVE_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_ACTIVE_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1030)
#define BIT_CA55_CORES_PCHN_ACTIVE_TIMEOUT_UPDATE_SET        BIT(24)

// REGISTER : CA55_CORES_PCHN_REQ_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_REQ_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1034)
#define BIT_CA55_CORES_PCHN_REQ_TIMEOUT_UPDATE_SET        BIT(24)

// REGISTER : CA55_CORES_PCHN_DENY_TIMEOUT_SET

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_DENY_TIMEOUT_SET_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x1038)
#define BIT_CA55_CORES_PCHN_DENY_TIMEOUT_SET_UPDATE_SET        BIT(24)

// REGISTER : CA55_CORES_PCHN_ACTIVE_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_ACTIVE_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2030)
#define BIT_CA55_CORES_PCHN_ACTIVE_TIMEOUT_UPDATE_CLR        BIT(24)

// REGISTER : CA55_CORES_PCHN_REQ_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_REQ_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2034)
#define BIT_CA55_CORES_PCHN_REQ_TIMEOUT_UPDATE_CLR        BIT(24)

// REGISTER : CA55_CORES_PCHN_DENY_TIMEOUT_CLR

#define CPU_SYS_COMM_GLB_CA55_CORES_PCHN_DENY_TIMEOUT_CLR_ADDR      (CPU_SYS_COMM_GLB_BASE_ADDR + 0x2038)
#define BIT_CA55_CORES_PCHN_DENY_TIMEOUT_UPDATE_CLR        BIT(24)

#endif
