
obj-$(CONFIG_AX_FBCDC)	+= fbcdc/
obj-$(CONFIG_AX_DMAXOR)	+= dmaxor/
obj-$(CONFIG_AX_DMADIM)	+= dmadim/
obj-$(CONFIG_AX_HWINFO)	+= ax_hwinfo/
obj-$(CONFIG_AX_DW_APB_TIMER) += apb_timer/
obj-$(CONFIG_AX_BWLIMITER) += bwlimiter/
obj-$(CONFIG_AX_MEMORY_DUMP) += memory_dump/
obj-$(CONFIG_AX_SYS_MAP) += sysmap/
obj-$(CONFIG_AX_OSAL)        += ../../../../../osal/linux/kernel/
obj-$(CONFIG_AX_HRTIMER)    += ax_hrtimer/
obj-$(CONFIG_AXERA_OS_MEM) += os_mem/
obj-$(CONFIG_ARCH_AXERA)       += ax_kmem_alloc/
