axera-drm-y := ax_drm_drv.o ax_drm_crtc.o ax_drm_gem.o ax_drm_plane.o ax_drm_fb.o ax_drm_vfb.o
axera-drm-y += ax_drm_virt_connector.o ax_drm_mipi.o ax_dphy_m31.o ax_display_hal.o

obj-$(CONFIG_DRM_AXERA) += axera-drm.o

obj-$(CONFIG_DRM_AXERA_HDMI) += ax_dw_hdmi.o
obj-$(CONFIG_DRM_AXERA_HDMI) += synopsys_hdmi/
