/**************************************************************************************************
 *
 * Copyright (c) 2019-2024 Axera Semiconductor Co., Ltd. All Rights Reserved.
 *
 * This source file is the property of Axera Semiconductor Co., Ltd. and
 * may not be copied or distributed in any isomorphic form without the prior
 * written consent of Axera Semiconductor Co., Ltd.
 *
 **************************************************************************************************/

#ifndef __AX_DSP_COMMON_H__
#define __AX_DSP_COMMON_H__

typedef enum {
    AX_SUCCESS = 0,
    AX_ERR_VDSP_ILLEGAL_PARAM = 0x80000001,
    AX_ERR_VDSP_INVALID_DEVID,
    AX_ERR_VDSP_INVALID_CHNID,
    AX_ERR_VDSP_EXIST,
    AX_ERR_VDSP_UNEXIST,
    AX_ERR_VDSP_NULL_PTR,
    AX_ERR_VDSP_NOT_CONFIG,
    AX_ERR_VDSP_NOT_SURPPORT,
    AX_ERR_VDSP_NOT_PERM,
    AX_ERR_VDSP_NOMEM,
    AX_ERR_VDSP_NOBUF,
    AX_ERR_VDSP_BUF_EMPTY,
    AX_ERR_VDSP_BUF_FULL,
    AX_ERR_VDSP_NOTREADY,
    AX_ERR_VDSP_BADADDR,
    AX_ERR_VDSP_BUSY,
    AX_ERR_VDSP_SYS_TIMEOUT,
    AX_ERR_VDSP_QUERY_TIMEOUT,
    AX_ERR_VDSP_OPEN_FILE,
    AX_ERR_VDSP_READ_FILE,
    AX_ERR_VDSP_INVALID_PARAM,
    AX_FAILURE,
} AX_VDSP_STS_E;

typedef struct {
    AX_U32 u32CMD;
    AX_U32 u32MsgId;
    AX_U32 u32Body[6];
} AX_DSP_MESSAGE_T;  //8 dword

typedef enum {
    AX_DSP_CMD_INIT = 0x0,
    AX_DSP_CMD_EXIT = 0x1,
    AX_DSP_CMD_SLEEP = 0x2,
    AX_DSP_CMD_POWEROFF = 0x3,
    AX_DSP_CMD_LOGLEVEL = 0x4,
    AX_DSP_CMD_FBCDC_CHANGE = 0x5,
    AX_DSP_CMD_TEST_COPY = 0x6,
    AX_DSP_CMD_TEST_GAUSSIBLUR = 0x7,
    AX_DSP_CMD_TEST_ADD = 0x8,
    AX_DSP_CMD_TEST_FBCDC = 0x9,
    AX_DSP_CMD_TEST_FBCDC_2 = 0xA,
    AX_DSP_CMD_TEST_DDRPERF = 0xB,
    AX_DSP_CMD_OPERATOR = 0x20,
    AX_DSP_CMD_OPERATOR_RESIZE,
    AX_DSP_CMD_OPERATOR_CVTCOLOR,
    AX_DSP_CMD_OPERATOR_JOINT_LR,
    AX_DSP_CMD_OPERATOR_SAD,
    AX_DSP_CMD_OPERATOR_KVM_SPLIT,
    AX_DSP_CMD_OPERATOR_KVM_COMBINE,
    AX_DSP_CMD_OPERATOR_MAP,
    AX_DSP_CMD_OPERATOR_NV12COPY,
    AX_DSP_CMD_OPERATOR_NV12Blending,
    AX_DSP_CMD_OPERATOR_COPY,
    AX_DSP_CMD_OPERATOR_NV12ROTATE,
    AX_DSP_CMD_OPERATOR_GDCMESH,
    AX_DSP_CMD_OPERATOR_SAD_EX,
    AX_DSP_CMD_OPERATOT_DFT_INIT,
    AX_DSP_CMD_OPERATOT_DFT_RUN,
    AX_DSP_CMD_OPERATOR_FIK = 0x100,
    AX_DSP_CMD_OPERATOR_RADAR = 0x101,
    AX_DSP_CMD_USER = 0x1000,
    AX_DSP_CMD_BUTT,
} AX_DSP_CMD_E;

typedef enum {
    E_Scale_U8,
    E_FilterSobel_U8,
    E_IntegralImage_U8U32,
    E_FilterSobel_U8S16,
    E_FilterGaussian_U8,
    E_RGBToYUV420_U8,
    E_YUV420ToRGB_U8,
    E_RGBToGray_U8,
    E_Transpose_U8,
    E_AffineTransform_U8,
    E_PerspectiveTransform_U8,
    E_YUV420To444_U8,
    E_ConnectedComponent_U8U16,
    E_Canny,
    E_MedianBlur_U8,
    E_Dilate_U8,
    E_Erode_U8,
    E_BoxFilter_U8,
    E_GuidedFilter_U8,
    E_BilateralFilter,
    E_PyrDown_U8,
    E_PyrDown_S16,
    E_LKTrackPoint_U8,
    E_LKTrackPoint_S16,
    E_LKPyrDown_U8,
    E_LKPyrDown_S16,
    E_CornerHarris,
    E_Census_U8,
    E_FlipHorizontal,
    E_FlipVertical,
    E_FilterFAST_U8,
    E_FilterFAST_S16,
    E_NonMaximaSuppression,
    E_Ncc,
    E_TemplateMatch,
    E_ExtractPoints_U8,
    E_ExtractPoints_S16,
    E_CornerHarris_NonMaxima,
    E_sort_S16,
    E_ExtractPoints_S32,
    E_ExtractKeyPoints_U8,
    E_CalcHist,
    E_EqualizeHist,
    E_PyrUp_U8,
    E_PyrUp_S16,
    E_SepFilter2d_R_U8,
    E_SepFilter2d_R_S16,
    E_SepFilter2d_D_U8,
    E_SepFilter2d_D_S16,
    E_Filter2d_R_U8,
    E_Filter2d_R_S16,
    E_Filter2d_D_U8,
    E_Filter2d_D_S16,
    E_LaplacianPyrDown_U8,
    E_LaplacianReconstruct_S16,
    E_LaplacianReconstruct2_S16,
    E_LBP_U8,
    E_MLBP_U8,
    E_ULBP_U8,
    E_MCT_U8U16,
    E_MCT_S16U16,
    E_BoxFilter_S16,
    E_FilterGaussian_R_U8,
    E_Convolve_RS_U8,
    E_Upsample2XNearest_I8,
    E_Laplacian3x3_U8S16,
    E_RemapNearest_I8,
    E_CornerShiTomasi,
    E_OpticalFlowBM_U8,
    E_PrepareHoughLines,
    E_GatherLocationsEq,
    E_HoughLinesTransform,
    E_HoughLinesExtract,
    E_CircleFilter_U8,
    E_CircleFilter_U16_U8
} AX_DSP_CV_FIK_ID_E;

#endif  //__AX_DSP_COMMON_H__
