/*
 *  ## Please DO NOT edit this file!! ##
 *  This file is auto-generated from the register source files.
 *  Any modifications to this file will be LOST when it is re-generated.
 *
 *  ----------------------------------------------------------------
 * Copyright (c) 2022 Realtek Semiconductor Corp. All rights reserved.
 *
 * SPDX-License-Identifier: LicenseRef-Realtek-Proprietary
 *
 * This software component is confidential and proprietary to Realtek
 * Semiconductor Corp. Disclosure, reproduction, redistribution, in whole
 * or in part, of this work and its derivatives without express permission
 * is prohibited.
 *  ---------------------------------------------------------------- */
#ifndef RTL906X_REG_DEFINE_H__
#define RTL906X_REG_DEFINE_H__

/* Modules */
#define MOD_CPU_SERIES
#define MOD_ACL
#define MOD_BUFFER_MANAGEMENT
#define MOD_QOS
#define MOD_NETWORK_MONITOR
#define MOD_GENERAL
#define MOD_VLAN
#define MOD_MAC_CONTROL
#define MOD_EAV
#define MOD_RRP
#define MOD_COUNTER
#define MOD_INTERRUPT
#define MOD_LED
#define MOD_DIAG
#define MOD_L2
#define MOD_CPU

#ifdef MOD_CPU_SERIES
/* Files */
#define FILE_CPU_SMI
#define FILE_CPU_EFUSE
#define FILE_CPU_ENGINE
#define FILE_CPU_VARIABLE
#define FILE_NIC
#define FILE_KEY
#define FILE_REG_LOCK
#define FILE_CPU_SPECIAL
#endif

#ifdef MOD_ACL
/* Files */
#define FILE_RANGE_CHECK
#define FILE_PIE_TEMPLATEGENARATOR
#define FILE_ACL
#endif

#ifdef MOD_BUFFER_MANAGEMENT
/* Files */
#define FILE_FLOW_CONTROL
#endif

#ifdef MOD_QOS
/* Files */
#define FILE_REMARKING
#define FILE_IGR_EGR_BANDWIDTH_CONTROL
#define FILE_TSN
#define FILE_QUEUE_MANAGEMENT
#endif

#ifdef MOD_NETWORK_MONITOR
/* Files */
#define FILE_MIRRORING
#endif

#ifdef MOD_GENERAL
/* Files */
#define FILE_TABLE_ACCESS
#define FILE_INTERFACE
#define FILE_RESET
#define FILE_BIST
#define FILE_I2C
#define FILE_HW_MISC
#define FILE_CHIP_VERSION
#endif

#ifdef MOD_VLAN
/* Files */
#define FILE_PORT_BASED_VLAN
#define FILE_VLAN_DECISION
#define FILE_PRIORITY_EXTRACTION
#define FILE_VLAN_TABLE
#endif

#ifdef MOD_MAC_CONTROL
/* Files */
#define FILE_PACKET_PARSER
#define FILE_ALE_MISC
#define FILE_RMA
#define FILE_TX_MODIFICATION
#endif

#ifdef MOD_EAV
/* Files */
#define FILE_EAV
#endif

#ifdef MOD_RRP
/* Files */
#define FILE_RLDP
#endif

#ifdef MOD_COUNTER
/* Files */
#define FILE_MIB_COUNTER
#endif

#ifdef MOD_INTERRUPT
/* Files */
#define FILE_GPIO
#define FILE_INTERRUPT
#define FILE_WOL
#endif

#ifdef MOD_LED
/* Files */
#define FILE_LED
#define FILE_UART
#endif

#ifdef MOD_DIAG
/* Files */
#define FILE_ALE_RELATED_DIAG
#define FILE_FLOW_CONTROL_DIAG
#define FILE_MIITEST_DIAG
#endif

#ifdef MOD_L2
/* Files */
#define FILE_L2_MISC
#define FILE_ADDR_TABLE_LOOKUP
#define FILE_SPANNING_TREE
#define FILE_SOURCE_MAC_LEARNING
#define FILE_802_1X
#define FILE_L2_ENTRY_NUM_CONSTRAIN
#define FILE_ATTACK_PREVENTION
#define FILE_STORM_CONTROL
#define FILE_PORT_ISOLATION
#define FILE_ROUTING
#define FILE_PORT_RELAY_DIS
#define FILE_EEE
#define FILE_LINK_AGGREGATE
#define FILE_STATEFUL
#endif

#ifdef MOD_CPU
/* Files */
#define FILE_CPU_DOMAIN
#define FILE_CLKRST
#define FILE_CPU_INFO
#endif

#endif /* RTL906X_REG_DEFINE_H__ */
