#include <rtthread.h>
#include <rthw.h>
#include <rtdevice.h>
#include "cmn.h"
#include "ax_common.h"
#include "dphyrx.h"
#include "drv_gpio.h"

//#define DPHYRX_DEBUG
static struct pin_dphyrx_info pin_dphyrx[48] = {
	{"RX1_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A9},
	{"RX1_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A10},
	{"RX1_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A11},
	{"RX1_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A12},
	{"RX1_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A13},
	{"RX1_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_INPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_1, AX_FUNC_SPI, "SPI_M2_MISO_m", AX_FUNC_GPIO, GPIO2_A14},
	{"RX0_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_MOSI_m", AX_FUNC_GPIO, GPIO2_A15},
	{"RX0_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_CS3_m", AX_FUNC_GPIO, GPIO2_A16},
	{"RX0_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_CS2_m", AX_FUNC_GPIO, GPIO2_A17},
	{"RX0_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_CS0_m", AX_FUNC_GPIO, GPIO2_A18},
	{"RX0_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_CS1_m", AX_FUNC_GPIO, GPIO2_A19},
	{"RX0_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX0, DPHYRX0_PIN_REG, ISP_RXCDPHY_0, AX_FUNC_SPI, "SPI_M2_CLK_m", AX_FUNC_GPIO, GPIO2_A20},
	/* pin_dphyrx1 */
	{"RX3_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A24},
	{"RX3_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A25},
	{"RX3_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A26},
	{"RX3_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A27},
	{"RX3_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A28},
	{"RX3_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_3, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A29},
	{"RX2_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A30},
	{"RX2_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A31},
	{"RX2_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A5},
	{"RX2_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A6},
	{"RX2_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A7},
	{"RX2_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX1, DPHYRX1_PIN_REG, ISP_RXCDPHY_2, AX_FUNC_NONE, NULL, AX_FUNC_GPIO, GPIO2_A8},
	/* pin_dphyrx2 */
	{"RX5_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A12},
	{"RX5_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_UART, "UART9_CTSN", AX_FUNC_COM_GPIO, COM_GPIO_A13},
	{"RX5_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A14},
	{"RX5_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_INPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_UART, "UART9_RXD", AX_FUNC_COM_GPIO, COM_GPIO_A15},
	{"RX5_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_UART, "UART9_RTSN", AX_FUNC_COM_GPIO, COM_GPIO_A16},
	{"RX5_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_5, AX_FUNC_UART, "UART9_TXD", AX_FUNC_COM_GPIO, COM_GPIO_A17},
	{"RX4_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A18},
	{"RX4_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_UART, "UART10_CTSN", AX_FUNC_COM_GPIO, COM_GPIO_A19},
	{"RX4_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A20},
	{"RX4_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_INPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_UART, "UART10_RXD", AX_FUNC_COM_GPIO, COM_GPIO_A21},
	{"RX4_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_UART, "UART10_RTSN", AX_FUNC_COM_GPIO, COM_GPIO_A22},
	{"RX4_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX2, DPHYRX2_PIN_REG, ISP_RXCDPHY_4, AX_FUNC_UART, "UART10_TXD", AX_FUNC_COM_GPIO, COM_GPIO_A23},
	/* pin_dphyrx3 */
	{"RX7_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A0},
	{"RX7_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_UART, "UART7_CTSN", AX_FUNC_COM_GPIO, COM_GPIO_A1},
	{"RX7_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A2},
	{"RX7_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_INPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_UART, "UART7_RXD", AX_FUNC_COM_GPIO, COM_GPIO_A3},
	{"RX7_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_UART, "UART7_RTSN", AX_FUNC_COM_GPIO, COM_GPIO_A4},
	{"RX7_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_7, AX_FUNC_UART, "UART7_TXD", AX_FUNC_COM_GPIO, COM_GPIO_A5},
	{"RX6_CKP_C0", AX_DPHY_LANE_1, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A6},
	{"RX6_CKN_C1", AX_DPHY_LANE_1, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_UART, "UART8_CTSN", AX_FUNC_COM_GPIO, COM_GPIO_A7},
	{"RX6_DP0_A0", AX_DPHY_LANE_0, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_NONE, NULL, AX_FUNC_COM_GPIO, COM_GPIO_A8},
	{"RX6_DN0_B0", AX_DPHY_LANE_0, AX_DPHY_N, AX_DPHY_INPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_UART, "UART8_RXD", AX_FUNC_COM_GPIO, COM_GPIO_A9},
	{"RX6_DP1_A1", AX_DPHY_LANE_2, AX_DPHY_P, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_UART, "UART8_RTSN", AX_FUNC_COM_GPIO, COM_GPIO_A10},
	{"RX6_DN1_B1", AX_DPHY_LANE_2, AX_DPHY_N, AX_DPHY_OUTPUT, PINMUX_DPHYRX3, DPHYRX3_PIN_REG, ISP_RXCDPHY_6, AX_FUNC_UART, "UART8_TXD", AX_FUNC_COM_GPIO, COM_GPIO_A11},
};

static void dphy_writew(uint16_t val, unsigned long addr)
{
#ifdef	DPHYRX_DEBUG
	rt_kprintf("Write 0x%lx, Val 0x%x\r\n", addr, val);
#endif
	ax_writew(val, addr);
}

static uint16_t dphy_readw(unsigned long addr)
{
	uint16_t val= ax_readw(addr);
#ifdef	DPHYRX_DEBUG
	rt_kprintf("Read 0x%lx, Val 0x%x\r\n", addr, val);
#endif
	return val;
}

static void dphy_writel(unsigned int val, unsigned long addr)
{
#ifdef	DPHYRX_DEBUG
	rt_kprintf("Write 0x%lx, Val 0x%x\r\n", addr, val);
#endif
	ax_writel(val, addr);
}

static uint32_t dphy_readl(unsigned long addr)
{
	uint32_t val= ax_readl(addr);
#ifdef	DPHYRX_DEBUG
	rt_kprintf("Read 0x%lx, Val 0x%x\r\n", addr, val);
#endif
	return val;
}

static void dphyrx_pin_dir_config(unsigned long ip_base, dphyrx_pin_lane_t lane, dphyrx_pin_sig_t sigbit, dphyrx_pin_dir_t dir)
{
	unsigned long addr;
	u32 temp;
#ifdef	DPHYRX_DEBUG
	int phy_index = (ip_base & 0x70000) >> 16;
#endif

	if (lane >= AX_DPHY_LANE_MAX) {
		AX_LOG_ERROR("%s: LANE_%d error\r\n", __func__, lane);
		return;
	}
#ifdef	DPHYRX_DEBUG
	rt_kprintf("[CDPHY%d]IP Base: 0x%lX, LANE_%d_%s %s\r\n", phy_index, ip_base, lane, sigbit ? "P" : "N", (AX_DPHY_OUTPUT == dir) ? "OUTPUT" : "INPUT");
#endif
	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7 + lane * 0x400;
	temp = dphy_readw(addr);
	temp &= ~ BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7_OA_LANE_LPTX_EN_OVR_VAL_BIT + sigbit);
	dphy_writew(temp, addr);

	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_8 + lane * 0x400;
	temp = dphy_readw(addr);
	temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_8_OA_LANE_LPTX_EN_OVR_EN_BIT);
	dphy_writew(temp, addr);

	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1 + lane * 0x400;
	temp = dphy_readw(addr);
	temp &= ~ BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1_OA_LANE_GPO_EN_BIT + sigbit);
	temp &= ~ BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1_OA_LANE_GPI_HYST_EN_BIT + sigbit);
	temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1_OA_LANE_GPI_EN_BIT + sigbit);
	dphy_writew(temp, addr);

	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7 + lane * 0x400;
	temp = dphy_readw(addr);
	temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7_OA_LANE_LPTX_PON_OVR_VAL_BIT + sigbit);
	if (AX_DPHY_OUTPUT == dir)
		temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7_OA_LANE_LPTX_EN_OVR_VAL_BIT + sigbit);
	else
		temp &= ~BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_7_OA_LANE_LPTX_EN_OVR_VAL_BIT + sigbit);
	dphy_writew(temp, addr);

	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_8 + lane * 0x400;
	temp = dphy_readw(addr);
	temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_8_OA_LANE_LPTX_PON_OVR_EN_BIT);
	temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_8_OA_LANE_LPTX_EN_OVR_EN_BIT);
	dphy_writew(temp, addr);

	addr = ip_base + CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1 + lane * 0x400;
	temp = dphy_readw(addr);
	if (AX_DPHY_OUTPUT == dir)
		temp |= BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1_OA_LANE_GPO_EN_BIT + sigbit);
	else
		temp &= ~BIT(CORE_DIG_IOCTRL_RW_AFE_LANE_CTRL_2_1_OA_LANE_GPO_EN_BIT + sigbit);
	dphy_writew(temp, addr);
}


void dphyrx_gpio_set_config(unsigned int gpio_num, gpio_func_e dir)
{
	int i, num, func;
	uint32_t off;
#ifdef	DPHYRX_DEBUG
	rt_kprintf("dir = %d\r\n", dir);
#endif
	if ((gpio_num < GPIO2_A5) || ((GPIO2_A20 < gpio_num) && (gpio_num < COM_GPIO_A0)) || (gpio_num > COM_GPIO_A31))
		return;

	dir = dir % 2;
	for (num = 0; num < 48; num++) {
		if (gpio_num == pin_dphyrx[num].gpio_num) {
			pin_dphyrx[num].fun4_6_def_dir = (dphyrx_pin_dir_t)dir;
			break;
		}
	}
#ifdef	DPHYRX_DEBUG
	rt_kprintf("num = %d\r\n", num);
#endif
	if (num == 48)
		return;

	i = num % 12;
	off = 0xC + i * 0xC;
	func = dphy_readl(pin_dphyrx[num].pinmux_reg_base + off);
	func &= ~GENMASK(18, 16);
	func |= PINMUX_GPIO_FUNC;
	dphy_writel(func, pin_dphyrx[num].pinmux_reg_base + off);
#ifdef	DPHYRX_DEBUG
	rt_kprintf("pinmux_reg_addr = %x\r\n", pin_dphyrx[num].pinmux_reg_base + off);
	rt_kprintf("func = %x\r\n", func);
#endif
	dphy_writel(func, pin_dphyrx[num].pin_dphyrx_reg_base + off);
	dphyrx_pin_dir_config(pin_dphyrx[num].rxcdphy_reg_base, pin_dphyrx[num].lane, pin_dphyrx[num].signal, pin_dphyrx[num].fun4_6_def_dir);
}
