#!/bin/sh

# configure network

# getting ip mode
# dhcp: default, get ip from server
# static: static IP, we need to configure following variable

# eth0
ipaddr0=
netdev0=
netmask0=
gateway0=

# eth1
ipaddr1=
netdev1=
netmask1=
gateway1=