#!/bin/sh

# configure network

# getting ip mode
# dhcp: default, get ip from server
# static: static IP, we need to configure following variable

# eth0
ipaddr0=192.168.1.22
netdev0=eth0
netmask0=255.255.255.0
gateway0=192.168.1.1

# eth1
ipaddr1=192.168.1.23
netdev1=eth1
netmask1=255.255.255.0
gateway1=192.168.1.1